name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 185.25.151.143
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /root/procode || git clone https://github.com/${{ github.repository }} /root/procode && cd /root/procode
            git pull origin main
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker-compose exec -T app npx prisma migrate deploy