name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 185.25.151.143
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Install Git if not present
            if ! command -v git &> /dev/null; then
                apt update -y
                apt install git -y
            fi
            
            # Install Docker if not present  
            if ! command -v docker &> /dev/null; then
                curl -fsSL https://get.docker.com -o get-docker.sh
                sh get-docker.sh
                systemctl enable docker
                systemctl start docker
            fi
            
            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
                curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
            fi
            
            # Clone or update repository
            if [ ! -d "/root/procode" ]; then
                git clone https://github.com/${{ github.repository }} /root/procode
            else
                cd /root/procode
                git pull origin main
            fi
            
            cd /root/procode
            
            # Create .env if not exists
            if [ ! -f ".env" ]; then
                cp .env.example .env
            fi
            
            # Deploy application
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            
            # Wait for database and run migrations
            sleep 15
            docker-compose exec -T app npx prisma migrate deploy